Add Awareness of Aliases To Avoid Duplicate Struct Error Check
ferranbt/fastssz pull request #46
Opened 2021-06-22 17:10 UTC by rauljordan

Currently, fastssz does not support the following structure of packages:

```
proto/
  v1/
    block.go
  v2/
    block.go
```

Where both files define a `type BeaconBlock struct` and v2 _includes_ v1. This is important for us in [Prysm](https://github.com/prysmaticlabs/prysm) because we want to use semantic versioning to create new types while leveraging some old code from previous versions to avoid code duplication. Attempting to generate ssz bindings for a package structure above will result in an error found in the `generateIR()` function:

`two structs found with the same name: BeaconBlock`

A workaround for our case was to define aliases such as

```go
package v2

type BeaconBlock struct{}

type BeaconBlockV2 = BeaconBlock
```
and call fastssz to generate bindings for BeaconBlockV2 to avoid the duplicate struct error. To achieve this, we needed to make fastssz aware of aliases as well when decoding AST structs.

2021-06-23 07:29 UTC, ferranbt commented
Could you add an example under spectests and regenerate everything with:
```
$ make build-spec-tests
```
This is a safe measure to make sure the new changes do not introduce something unexpected.

2021-06-27 21:03 UTC, ferranbt requested changes
Please add an example in the spectests folder and run:
```
$ make build-spec-tests
```
so that we are sure that the change implements the correct behaviour.

2021-07-02 14:36 UTC, rauljordan commented
Hi @ferranbt, just pushed the example and it builds as expected

2021-07-02 14:37 UTC, rauljordan commented on spectests/structs.go
> +type BeaconBlockV2 = BeaconBlockV3
Previously, this would complain

2021-07-02 19:06 UTC, ferranbt requested changes

2021-07-02 19:06 UTC, ferranbt commented on spectests/structs_encoding.go
> +	size = 0
Is this correct?

2022-07-30 12:31 UTC, closed without merging