Altair support
ferranbt/fastssz pull request #59
Opened 2021-08-19 13:54 UTC by ferranbt

This PR adds support for the new types in Altair as per version v1.1.0 of the spectests.

2021-08-23 21:01 UTC, prestonvanloon commented
Any update on this? we are hoping to unblock our atlair code for final review as soon as possible.

Let us know how we can help

2021-08-31 20:17 UTC, prestonvanloon commented
Any update on this? We're hoping to close out remaining Altair items this week.

2021-09-01 12:39 UTC, kasey commented
@ferranbt github didn't create a backlink from this PR comment, so I'll link it here for visibility https://github.com/ferranbt/fastssz/pull/60#issuecomment-908540639

2021-09-02 16:36 UTC, kasey requested changes

2021-09-02 16:36 UTC, kasey commented on sszgen/hash.go
> +			appendFn = "PutBytes"
Should this be `v.e.s % 32 != 0`?

2021-09-05 18:14 UTC, merged